service: default
runtime: custom
env: flex
# entrypoint: gunicorn --bind:$PORT main:app
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  
resources:
  cpu: 2
  memory_gb: 2.5
  disk_size_gb: 20